import type { Metadata } from "next";
import "@/styles/globals.css";
import { Montserrat } from 'next/font/google'
import NavBar from "@/components/ux/nav-bar";
import Footer from "@/components/ux/footer";
const montserrat = Montserrat({ subsets: ['latin'] })
import 'leaflet/dist/leaflet.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "- IE Builders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >

        <NavBar></NavBar>
        <main className="bg-[#F2F6F5] min-h-screen">
          <ToastContainer theme="colored" position="bottom-right" />
          {children}
        </main>
        <Footer></Footer>

      </body>
    </html>
  );
}
